### ISSUE TITLE
bug: view sometimes not refreshed

### ISSUE THREAD

**Issue by kaspar030** [murdock-ng/murdock-html#4]
leaving a tab open, if the connection drops for any reason (network down, murdock server restart), the SPA just stops updating.

A reload is needed to reconnect.

I'd expect the SPA to automatically reconnect on timeout or connection drop.

**Comment by aabadie** [comment]
Hmm, it was supposed to be fixed by a9df047273668ff4b0bf802f29799f34067b0635 and is already deployed. Will check.

**Comment by aabadie** [comment]
I just tried to disconnect  and reconnect my network and saw this in the UI web console:

![image](https://user-images.githubusercontent.com/1375137/204246540-9144efb0-c620-425c-b3b0-1bf07bdff858.png)

So it seems to work. The last GET was issued right after the websocket reopened and it refreshed the page (you don't notice but it does if there are new items)

**Comment by kaspar030** [comment]
Hm, I keep coming to ci.riot-os.org with a seemingly stuck version, and a reload fixes it. I'll try to keep the console open to see what's going on!

**Comment by aabadie** [comment]
I also have something weird and I think there's indeed a bug lying somewhere. The websocket auto reconnect works AFAICS but the refresh is not always triggered indeed.

**Comment by kaspar030** [comment]
It happened again.

As you can see from the tooltip, it seems the websocket is alive, but as you said, there was no refresh.
*edit* the tooltip was not captured, but it showed the running branch as done.

![image](https://user-images.githubusercontent.com/4679640/204290262-42e05dfc-ca97-4472-b1d3-d75ddccf6194.png)

**Comment by aabadie** [comment]
it should be fixed by 2dee4778f45523b082623e07e86af5ec9569b10d

**Comment by kaspar030** [comment]
Seems fixed.
